train:
    data_paths:
        features: data/X_train.csv
        label: data/y_train.csv
    preprocessing:
        scale: true
        imputation:
            method: mice_simple_imputer  # Specify the custom imputation method
            arguments:
                mice:
                    estimator_params:
                        n_estimators: 100  # Initial values for n_estimators
                        max_depth: 5      # Initial values for max_depth
                    mice_params:
                        max_iter: 10     # Initial value for max_iter
                        num_corr_features: 10  # Initial value for num_corr_features
                        imputation_order: ascending  # Initial value for imputation_order
                    simple_params:
                        strategy: mean  # Initial value for the strategy
                    num_corr_features: 10
        outliers_detection:
            method: isolation_forest
            arguments: {}
        feature_selection:
            method: lasso
            arguments: 
                alpha: 0.9
        execution_order:
            - imputation
            - outliers_detection
            - feature_selection               
    model_type: ada
    model_config: {n_estimators: 50, learning_rate: 1}
    cross_validation: 5
    results_path: results/overview.csv

evaluate:
    run: True
    data_paths:
        features: data/X_test.csv
        label: data/y_test_ada_mice.csv